[versions]
# jetpack releases https://developer.android.com/jetpack/androidx/versions
androidx-junit = "1.3.0"
compose-bom = "2025.12.01"
datastore = "1.2.0"
hamcrest = "3.0"
hilt-core = "2.57.2"
hilt-android = "1.3.0"
junit = "4.13.2"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
lifecycle = "2.10.0"
mockito-kotlin = "6.1.0"
navigation = "2.9.6"
opencsv = "4.1"
orchestrator = "1.6.1"
robolectric = "4.16"
room = "2.8.4"
test-core = "1.7.0"
uiautomator = "2.3.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.12.2" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-android" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test-core" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling-core = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
compose-material3 = { module = "androidx.compose.material3:material3" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
hilt-android-core = { module = "com.google.dagger:hilt-android", version.ref = "hilt-core" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-core" }
javafaker = { module = "net.datafaker:datafaker", version = "1.9.0" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-compiler = { module = "androidx.room:room-compiler", version.ref="room"}
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

[plugins]
android-app = { id = 'com.android.application', version = "8.13.2" }
# Add the Compose Compiler Gradle plugin, the version matches the Kotlin plugin
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-core" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin" }
